name: Build and Deploy
on: # ç›‘å¬ main åˆ†æ”¯ä¸Šçš„ push äº‹ä»¶
  push:
    branches:
      - action-test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # æ„å»ºç¯å¢ƒä½¿ç”¨ ubuntu
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout # å°†ä»£ç æ‹‰åˆ°è™šæ‹Ÿæœº
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install and Build # ä¸‹è½½ä¾èµ– æ‰“åŒ…é¡¹ç›®
        run: |
          npm install
          npm run build

      - name: Deploy ğŸš€ # éƒ¨ç½²
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages # ä½¿ç”¨æ ‡å‡†çš„ gh-pages åˆ†æ”¯
          folder: dist # è¿™é‡Œå¡«æ‰“åŒ…å¥½çš„ç›®å½•åç§°
          clean: true # æ¸…ç†ç›®æ ‡åˆ†æ”¯
          single-commit: true # ä½¿ç”¨å•ä¸ªæäº¤
